# Site settings
title: A blog about Adrija Barvadheesh
description: Technical Resume-Adrija Barvadheesh
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adrija Barvadheesh
user_description: MBA-MS Student @ Leeds School of Business
email: adrija.barvadheesh@colorado.edu
twitter_username: https://www.linkedin.com/in/adrijabarvadheesh/
github_username:  https://github.com/Adrija-B
gplus_username:  hehe

# Google-analytics
google-analytics:
  id: "299950535"

exclude: ['package.json', 'src' , 'node_modules']
